### ISSUE TITLE
Apple Watch unlock

### ISSUE THREAD

**Issue by egore24** [the-Quert/XPS-9360-macOS#1]
Hello and thank you for your efforts with this repo! Have you had any success with Apple Watch unlock? I have the same machine as you (except QHD display and a different SSD); enabling Apple Watch unlock shows the 9360 enabling the feature successfully. When locking the screen, it does successfully unlock from that state once, but subsequent attempts fail and also fail from a full sleep. 

It seems the ability is there, but not reliability. Thanks much!

**Comment by ghost** [comment]
Hello and thanks for your support !! Cause I don't have Apple Watch to test the unlock function, I also have to figure out how to fix the problem.
Will keep trying to enhance the unlock function !

**Comment by egore24** [comment]
Excellent! Thank you for this. I’d be happy to test for you as you proceed with the Apple Watch unlock function.

**Comment by ghost** [comment]
Hello, I have complete compiling bluetooth function.
The kexts for DW1560 have been put in /BCM94352z in my repository.
Please follow the steps below:

/Library/Extentions has to include
1. [AirportBrcmFixup.kext] 
2. [BrcmFirmwareRepo.kext] 
3. [BrcmPatchRam2.kext]
4. [Lilu.kext]

Furthermore, you have to remove the kexts below from /CLOVER/kexts/Others.
1. [AirportBrcmFixup.kext] 
2. [BrcmFirmwareRepo.kext] 
3. [BrcmPatchRam2.kext]

Remember to rebuild cache and reboot after you add kexts to /Library/Extensions.
About the command to rebuild cache, I have put the script to /Commands/rebuild_cache.sh in my repository.

My testing result: Bluetooth is able to connect with Bluetooth Audio, and Airdrop, all went well !!
After laptop wake up from sleep, Bluetooth is still remain available.
Please let me know if it went well after you test with Apple Watch.

**Comment by egore24** [comment]
Thank you so much for your efforts! I rearranged things as you mentioned and all continues to work as above. 

However, the Apple Watch Unlock behavior remains the same as before. Works one time after activation, then not. 

Only additional question is after moving Kexts as you mentioned, leaves lilu Kext both in /Clover/Kexts as well as now /Library/Extensions. I’m guessing to remove the Clover copy, but doubt that has anything to do with the Watch behavior. Thanks again!

**Comment by ghost** [comment]
Since the situation still remains due to your test on Apple Watch, I will keep trying to improve the connection problem.

**Comment by egore24** [comment]
Thank you for your efforts!

**Comment by ghost** [comment]
After digging into research, other users who have been used DW1560 / DW1830 both have issue with bluetooth problem on Apple Watch unlock function. According to tests on DW series Wifi+BT card, there is nothing can do with Apple Watch unlock function. 

If there are other solutions to improve, I will keep update with fixes.

**Comment by egore24** [comment]
Ok, thank you for your efforts.

**Comment by ghost** [comment]
Since still no solution for solving Apple Watch Unlock on both DW1830 and DW1560, case closed.
If there is new update for solving in the future, will be updated in README.

**Comment by ghost** [comment]
New solution is provided...
Copy all kexts from path /DW1560 to /Library/Extensions, and then running rebuild_cache.sh in Commands to  fix the permission.

Please let me know if Apple Watch unlocking  function is compatible with this repo.

**Comment by egore24** [comment]
I will give this a try. Should the kexts in /DW1560 be only installed into /L/E and not injected via Clover? Specifically, Lulu.kext is only installed into /L/E? Thanks.

**Comment by egore24** [comment]
Still did not work.

**Comment by egore24** [comment]
One possible direction to investigate: Handoff from Apple Watch to Hack does not work. It does work Apple Watch to iPhone though.

**Comment by ghost** [comment]
Hi, new kexts is uploaded to /DW1560. Kexts in /DW1560 should only be installed into /L/E.
Feel free to test with Apple Watch.
BTW, pls let me know how's it going.

**Comment by egore24** [comment]
Thanks for this. I am doing a wipe of the hard drive and fresh install of Catalina 10.15.3. I will let you know how your repo works, specifically Apple Watch functionality.

**Comment by egore24** [comment]
Hello. I have been working with your repo on a pristine reinstall of Catalina. I can report about the same behavior as before; that being the AW unlock feature does work for a single session as much as it is needed without issue. However, a login unlock from a locked state does not work. And, when manually unlocked and back into the OS, unlock no longer works either. 

It can be re-enabled by turning off bluetooth functionality on the Hack and disabling the AW unlock in the CP, then re-enabling Bluetooth on the Hack and then re-enabling the unlock feature. After doing so, functionality returns for another session. 

The cycle repeats.

Just wondering why BrcmFirmwareData.kext is chosen to be used in L/E when its repo states BrcmFirmwareRepo.kext is to be used in L/E?

I hope this helps and thanks for your continued work on this issue!

**Comment by egore24** [comment]
Additionally, within a 'working' session, there appears to be a time-out issue where the AW no longer unlocks anything on the Hack. The bluetooth menubar icon remains with the 'binded' status, but no AW functionality.

A turn off Bluetooth and uncheck in CP, then reversing allows functionality to return.

**Comment by ghost** [comment]
Will keep trying...

**Comment by yongjiajun** [comment]
Any update regarding this matter?

**Comment by ghost** [comment]
> Any update regarding this matter?

Updates follow...[here](https://github.com/the-Quert/XPS-9360-macOS/issues/16)

**Comment by ctermiii** [comment]
94360cs2 is just ok.

**Comment by egore24** [comment]
The superior card of choice, which also resolves this issue, making AppleWatch unlock functionality work as expected is BCM94360NG. An M.2 form factor, direct replacement card. This solution will close this issue.
