### ISSUE TITLE
camera isn't working

### ISSUE THREAD

**Issue by ymmshi** [the-Quert/XPS-9360-macOS#10]
USB information
https://tva1.sinaimg.cn/large/0082zybply1gbwe0gnj0xj30jc0mq40c.jpg
https://tva1.sinaimg.cn/large/0082zybply1gbwe4tqhywj30u00wegr2.jpg
But camera can't be found!
https://tva1.sinaimg.cn/large/0082zybply1gbwe38qz7gj31220u0adf.jpg
FaceTime is not ok too.
https://tva1.sinaimg.cn/large/0082zybply1gbwe419fyjj31080sqjty.jpg

**Comment by ghost** [comment]
![Screen Shot 2020-02-16 at 6 07 52 PM](https://user-images.githubusercontent.com/19849526/74602764-4ac03780-50e7-11ea-9994-32600272a681.png)
![Screen Shot 2020-02-16 at 6 06 38 PM](https://user-images.githubusercontent.com/19849526/74602767-4eec5500-50e7-11ea-86d5-592712f0235c.png)

Cause camera function is seldom used, it's been disabled in Bios settings (See the last point in Bios settings from my guide.)

After testing and enabled camera in BIOS, camera is recognized and working fine as normal.
Pls check your Bios settings again...
