### ISSUE TITLE
camera doesn't work

### ISSUE THREAD

**Issue by nmm2401** [the-Quert/XPS-9360-macOS#11]
![Screen Shot 2020-02-16 at 23 12 00](https://user-images.githubusercontent.com/61118105/74608203-be773a00-5111-11ea-924d-ac9ef60f6811.png)
I have enabled camera in bios, but don't work

**Comment by ghost** [comment]
![Screen Shot 2020-02-16 at 6 07 52 PM](https://user-images.githubusercontent.com/19849526/74602764-4ac03780-50e7-11ea-9994-32600272a681.png)
![Screen Shot 2020-02-16 at 6 06 38 PM](https://user-images.githubusercontent.com/19849526/74602767-4eec5500-50e7-11ea-86d5-592712f0235c.png)

Cause camera function is seldom used, it's been disabled in Bios settings (See the last point in Bios settings from my guide.)

After testing and enabled camera in BIOS, camera is recognized and working fine as normal.
Pls check your BIOS settings again...

**Comment by nmm2401** [comment]
i have check in bios too

**Comment by nmm2401** [comment]
btw, maybe different camera ID ?

**Comment by ghost** [comment]
Camera is connected and recognized with USB bus, maybe there is something wrong with your USB bus.
As your port type is same as mine...there is nothing to do with camera ID in whole repo.
In theory, USB port is all opened with the USBInjectAll.kext, and your port is also opened.

**Comment by nmm2401** [comment]
have u updated new ssdt, ssdt-pwrb.aml, need compile dsl or just copy aml file

**Comment by ghost** [comment]
Just copy aml file, but "shutdown dialog" is not gonna appear when Power Button is pressed. 
Need more work to improve...

**Comment by nmm2401** [comment]
nice, keep your good work bro

**Comment by ghost** [comment]
BTW, if you have the same specs as mine, just copy the aml file.. if not, still need to compile the .dsl file which I have put in /DSDT.

**Comment by nmm2401** [comment]
okay so now i will compile

**Comment by nmm2401** [comment]
u just update ssdt or something else

**Comment by ghost** [comment]
Only update SSDT-PWRB in repo. Everything is working perfectly, still need improve and testing on Power Button...even that function is never used.

**Comment by nmm2401** [comment]
oh thank u so much for your work

**Comment by nmm2401** [comment]
![Screen Shot 2020-02-17 at 23 26 00](https://user-images.githubusercontent.com/61118105/74671064-f7c8ac00-51dc-11ea-9b1f-ce43ae08df6d.png)
warning but everything it's ok

**Comment by nmm2401** [comment]
oh need to set hibernatemode again ?

**Comment by nmm2401** [comment]
different cpu, so i need ssdt-cpuf.dsl or not ?

**Comment by ghost** [comment]
Nope, you need to create your own CPUFriend and its SSDT.

**Comment by nmm2401** [comment]
how to create ssdt-cpuf. i have create cpufriend kext by using onekey-cpufriend

**Comment by ghost** [comment]
Follow the guide from acidanthera...
[https://github.com/acidanthera/CPUFriend/blob/master/Instructions.md](url)

**Comment by nmm2401** [comment]
no result ...

**Comment by nmm2401** [comment]
![Screen Shot 2020-02-18 at 14 42 10](https://user-images.githubusercontent.com/61118105/74714287-da3b2700-525c-11ea-8c90-8c770a46bb26.png)
so what value i should fill,  me i5-8250u, not same your cpu

**Comment by ghost** [comment]
CPU info is not needed to fill.  
Follow the guide from acidanthera:
**Usage of ResourceConverter.sh
--kext /path/to/file Create CPUFriendDataProvider.kext with information provided by file.

--acpi /path/to/file Create ssdt_data.dsl with information provided by file.**

You need:
/System/Library/Extensions/IOPlatformPluginFamily.kext/Contents/PlugIns/X86PlatformPlugin.kext/Contents/Resources/Mac-827FB448E656EC26.plist
to generate SSDT with the guide above.

**Comment by nmm2401** [comment]
thank u, i will try

**Comment by nmm2401** [comment]
i can't open kext file

**Comment by egore24** [comment]
Pretty simple. Right click on kext file and 'show package contents'.

**Comment by nmm2401** [comment]
i can't generate , hope others user using same cpu (i5-8250u) ....

**Comment by ppoffice** [comment]
@nmm2401 @ymmshi #10 
This one may help: https://github.com/the-darkvoid/XPS9360-macOS/issues/146

**Comment by ymmshi** [comment]
> @nmm2401 @ymmshi #10
> This one may help: [the-darkvoid/XPS9360-macOS#146](https://github.com/the-darkvoid/XPS9360-macOS/issues/146)

Although I don't know why, it works well. Thanks for your help!

**Comment by ghost** [comment]
Kext updated, case close.
