### ISSUE TITLE
Which files need to be reconfigured for different CPU and graphics card？

### ISSUE THREAD

**Issue by carking** [the-Quert/XPS-9360-macOS#13]
Hello, my laptop is XPS 9350, because I cannot find the latest 9350 efi on github, so I consider your configuration.

9350 and 9360 are basically the same, but my CPU is 6560U (iris540 graphics card), may I ask which files needs to change to fit my machine?

And how is the battery life of the hackintosh? I am using another efi right now, my screen is 3k model, the battery drops 1% every two minutes, is that normal? The bottom cover will also become hot (the fan will not work actively)

thank you!!

**Comment by carking** [comment]
I'll use one key cpufriend to generate the new CPUFriend.kext and CPUFriendDataProvider.kext, Is there anything else I needs to change?

**Comment by ghost** [comment]
In config.plist, change ig-platform-id  to  "0x19260000", and change the product model in SMBIOS to "MacBookPro13,1"

**Comment by carking** [comment]
> In config.plist, change ig-platform-id to "0x19260000", and change the product model in SMBIOS to "MacBookPro13,1"

Okay, thanks！
Do you have any battery drain issue? my screen is 3k model, the battery drops 1% every two minutes, is that normal?

**Comment by ghost** [comment]
My screen is FHD. I've heard 3k screen may cause battery drain, but if CPUFriend is set, it would be improved.
