### ISSUE TITLE
OC Support

### ISSUE THREAD

**Issue by egore24** [the-Quert/XPS-9360-macOS#14]
Hello. Again, thank you for keeping your repo up to date! 

Will you be making a complete move to OpenCore soon? I have tried to use the OC folder you have here, but I am unable to boot into the OS with it. Is the OC folder up to date and working for you? I have an HDi screen, if that makes a difference reference your OC configuration.

Thanks much.

**Comment by ghost** [comment]
Default bootloader is Clover for now, and OC support is testing on the way !
Since OC's structure has multiple changes between each version, testing would need more strengths.
When OC is configured and tested, default bootloader would be migrated from Clover to OC.

**Comment by marmasin** [comment]
Thansk for your OC folder. I actually did not used your config and all SSDT I ve made myself.
Most of thing are working bit CPU is not recognised.

**Comment by ghost** [comment]
@marmasin OC support is still on beta. Feel free to share your config to help with more improvement.

**Comment by marmasin** [comment]
@the-Quert thank you for your support. I manage to resolve Usupported CPU. Using  OCSanity I ve cleared my config and kext and now i see my proc. I am trying to upload my config but file dont know how. So Im sending link https://we.tl/t-u7RKLAQj7O
Also here is my system overview.
![Screenshot 2020-05-11 at 20 46 52](https://user-images.githubusercontent.com/62131250/81599320-bc4b1180-93c8-11ea-8fb8-a6d8530380d6.png)

**Comment by TaiPhamD** [comment]
OC is labeled as "unstable". In what way is it unstable?

**Comment by ghost** [comment]
Since OC is on beta, and under testing, configuration is still on the way.

> OC is labeled as "unstable". In what way is it unstable?

**Comment by ghost** [comment]
@egore24 @marmasin @TaiPhamD 
OpenCore beta configuration is out ! 
For more info about migrating from Clover to OpenCore... see [here](https://github.com/the-Quert/XPS-9360-macOS/blob/master/README.md#Migrate-bootloader-from-Clover-to-OpenCore)

Feel free to report any issues, and maybe I will do it as soon as I can.

**Comment by egore24** [comment]
This is great to hear! I did try, but was unable to boot. OC selection screen was there and progressed to the Apple icon, but no progress bar, no boot. The only things I changed to the OC config was replace Serial, Board Serial, SMUUID, etc. I also deleted AirportBrcmFixup.kext, BrcmBluetoothInjector.kext, BrcmFirmwareData.kext, BrcmPatchRAM3.kext since I have BCM94360NG card installed. I wouldn't think any of these changes would have caused the machine to not boot, but do you think it's possible? Thanks.

**Comment by ghost** [comment]
Before migration, press `F11` on Clover boot section to reset NVRAM, and running `trans.sh` to clear caches of Clover.
If deleting`AirportBrcmFixUp`, `BrcmBluetoothInjector`, `BrcmFirmwareData`, `BrcmPatchRAM3`, you should delete them in `config.plist/Kernel` as well.


Feel free to report any issues, and maybe I will do it as soon as I can.

**Comment by egore24** [comment]
Still having issues. Also, it looks like your OC scripts reference Clover folder and tools from clover. Is that in fact accurate? Thanks.

**Comment by ghost** [comment]
Shell script in OC is reference from Clover, but it only involves `tools/iasl` to compile DSDTs.
As a matter of fact, compiling process is working fine.

Feel free to report any issues, and maybe I will do it tomorrow.

> Still having issues. Also, it looks like your OC scripts reference Clover folder and tools from clover. Is that in fact accurate? Thanks.

**Comment by ctermiii** [comment]
I may know the reason.
how you copied the files? you should check every directory in OC

> Still having issues. Also, it looks like your OC scripts reference Clover folder and tools from clover. Is that in fact accurate? Thanks.

**Comment by ghost** [comment]
XPS_OC.sh updated.
When compiling DSDTs, `tools` under parent directory is no needed.
`OC/s_tools` is added to support DSDTs compiling process under OC.

Caution: During migration, be sure to backup previous version of the configuration in EFI partition.

Feel free to report any issues, and maybe I will do it tomorrow.

**Comment by egore24** [comment]
Thanks for the efforts. I have been able to compile the DSDTs okay now, but still not able to boot. I've attached a pair of verbose screenshots. Maybe that will help. Thanks!
![IMG_7516](https://user-images.githubusercontent.com/25514547/81981495-fb11df00-95f5-11ea-8aa5-884e26a94450.jpeg)
![IMG_7518](https://user-images.githubusercontent.com/25514547/81981519-0533dd80-95f6-11ea-93a4-c2c05518caee.jpeg)

**Comment by vrondena** [comment]
9360 with i7-7500u, tried different configurations acpi, kexts, config same problem at boot still much to develop OC for Dell xps

**Comment by TaiPhamD** [comment]
> 9360 with i7-7500u, tried different configurations acpi, kexts, config same problem at boot still much to develop OC for Dell xps

I am using OC right now with i7-8550u and don’t have a problem. If you are using it to boot up Mac OS usb installer make sure to enable the USBreleaseownership quirk .

**Comment by vrondena** [comment]
for now boot from disk but same problem with USB installer sorry but..where I enable it, USBreleaseownnership ? on config - quirk don't have this voice

**Comment by vrondena** [comment]
yyyyesssss, with usb and activatedUSBreleaseownership with Opencore config the present item i always used ProperTree.thank you very much for help, with disk boot how to do?

**Comment by ghost** [comment]
@egore24 
More improvements would be done in future releases.
For now, it's recommended to use `Clover` as default boot loader.
- Feel free to report any issues, and maybe I will do it tomorrow.

**Comment by egore24** [comment]
Great job on OC progress. I am running your latest commit and things so far, seem very nice. 

Of course with the different WiFi/BT card, I deleted the BCRM/Airport/FakeWiFi kexts as well as the associated entries in config. Card is working natively.

I think the only other difference with my machine to yours is mine is a QHD display. Anything I need to change for the display difference? It is working just fine, but if there is something to change for it, please let me know.

Thanks again!

**Comment by ctermiii** [comment]
> Great job on OC progress. I am running your latest commit and things so far, seem very nice.
> 
> Of course with the different WiFi/BT card, I deleted the BCRM/Airport/FakeWiFi kexts as well as the associated entries in config. Card is working natively.
> 
> I think the only other difference with my machine to yours is mine is a QHD display. Anything I need to change for the display difference? It is working just fine, but if there is something to change for it, please let me know.
> 
> Thanks again!

you mean the latest OC config？ good news， I will have a try tonight。

**Comment by egore24** [comment]
I mean the commit from today.

**Comment by ctermiii** [comment]
> I mean the commit from today.
> […](#)

ok,got it.
thanks, I will try OC 0.5.8 tonight.

**Comment by vrondena** [comment]
how fix restart after shutdown ?
[config.plist.zip](https://github.com/the-Quert/XPS-9360-macOS/files/4696539/config.plist.zip)

**Comment by ghost** [comment]
`OpenCore` is just modified and updated.
Try `OpenCore` as bootloader,  cause more detailed power management is just configured with `DSDT` in OC.

- Feel free to report any issues, and maybe I will do it tomorrow.

**Comment by vrondena** [comment]
> how fix restart after shutdown ?
> [config.plist.zip](https://github.com/the-Quert/XPS-9360-macOS/files/4696539/config.plist.zip)

reset/clear nvram solve

**Comment by theQuert** [comment]
OC is announced as default bootloader. If more issues found in the future, feel free to file.
