### ISSUE TITLE
OC configure error

### ISSUE THREAD

**Issue by ctermiii** [the-Quert/XPS-9360-macOS#15]
there's something wrong in the oc config.
I tried just now ,can't boot.
some bcmxxx errors

**Comment by ghost** [comment]
OC is still under configuration.
Try to remove Brcm kexts, and its info in config.plist, then see how it goes.

**Comment by ctermiii** [comment]
actually,i have already tried delete brcm kexts and edit the config.plst sometimes, but its still wrong.
now I am using your clover configure. thanks.

**Comment by ghost** [comment]
OC support is under configuration, more configuration about OC is on the way.

**Comment by ctermiii** [comment]
thanks .you are a good guy.

**Comment by ctermiii** [comment]
thanks.
