### ISSUE TITLE
Bcm94360cs2 WiFi/BT Option

### ISSUE THREAD

**Issue by egore24** [the-Quert/XPS-9360-macOS#16]
Hello, I see you have Bcm94360cs2 listed as an option for the WiFi/BT card. With this card not being a M.2 form factor, how do you suggest this card be installed into the 9360? Is there an install solution that allows the laptop cover to be properly installed after placing the Bcm94360cs2? Thanks much.

**Comment by ghost** [comment]
To install BCM94360CS2, we need an adapter to convert slot to M.2 form. 
The link for adapter is provided [here](https://item.taobao.com/item.htm?ut_sk=1.XWsc4dMsS34DACEUylrXQaEj_21380790_1586529493675.Copy.1&id=597934983608&sourceType=item&price=35.96-49.56&suid=7553B292-D311-408D-85D2-302BC76C8C4F&un=e4e32345609137314e33a31e70d32733&share_crt_v=1&spm=a2159r.13376460.0.0&sp_tk=wqJLbFc1MTlSR0xySsKi&cpp=1&shareurl=true&short_name=h.V6caJaX&sm=8accb9&fbclid=IwAR3aCmKWQWe-w_8d8E-2FpoPXMUdvvSH2vvoEDgG-37IuoLfsCjzrSq8E0k&app=chrome).

I've install BCM94360CS2 successfully, no more Brcm kext is needed.
I believe Apple Watch Unlock problem would be solved definitely.

**Comment by ctermiii** [comment]
I used the adapter too.
but I didn't find a better place ,its hard to cover the back.
could you take a picture?

**Comment by ghost** [comment]
I placed it to the following position...

![1](https://user-images.githubusercontent.com/19849526/79060493-284a3500-7cb8-11ea-8877-b2d04777afc3.JPG)

![2](https://user-images.githubusercontent.com/19849526/79060487-1ec0cd00-7cb8-11ea-9ebd-63cb07a4eb70.JPG)

**Comment by ctermiii** [comment]
good choice. thanks.

**Comment by ctermiii** [comment]
perfect place !

**Comment by ctermiii** [comment]
btw: bios 2.13.0 is ok for your configration.

**Comment by egore24** [comment]
> I placed it to the following position...
> 
> ![1](https://user-images.githubusercontent.com/19849526/79060493-284a3500-7cb8-11ea-8877-b2d04777afc3.JPG)
> 
> ![2](https://user-images.githubusercontent.com/19849526/79060487-1ec0cd00-7cb8-11ea-9ebd-63cb07a4eb70.JPG)

With this placement, are you able to completely install the rear cover? If so, any issues? Thanks.

**Comment by ghost** [comment]
> btw: bios 2.13.0 is ok for your configration.

BIOS version would add to README.

**Comment by ghost** [comment]
> > I placed it to the following position...
> > ![1](https://user-images.githubusercontent.com/19849526/79060493-284a3500-7cb8-11ea-8877-b2d04777afc3.JPG)
> > ![2](https://user-images.githubusercontent.com/19849526/79060487-1ec0cd00-7cb8-11ea-9ebd-63cb07a4eb70.JPG)
> 
> With this placement, are you able to completely install the rear cover? If so, any issues? Thanks.

Sure, rear cover is able to be install without any issues.

**Comment by egore24** [comment]
I ordered this: https://www.ebay.com/itm/Apple-MacBook-Air-13-A1466-2015-WiFi-Wireless-BT-Card-BCM94360CS2-653-0023/184227170229?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649

and this

https://www.amazon.com/gp/product/B07JFYSNVL/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

since I wasn't able to order the adapter from the Chinese site. Hopefully I'll be able to get this adapter to fit as well, albeit a bit bulkier. I'll report back for others if this works or not.

**Comment by ctermiii** [comment]
> I ordered this: https://www.ebay.com/itm/Apple-MacBook-Air-13-A1466-2015-WiFi-Wireless-BT-Card-BCM94360CS2-653-0023/184227170229?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649
> 
> and this
> 
> https://www.amazon.com/gp/product/B07JFYSNVL/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
> 
> since I wasn't able to order the adapter from the Chinese site. Hopefully I'll be able to get this adapter to fit as well, albeit a bit bulkier. I'll report back for others if this works or not.

i dont think there is enough place for your adapter.

**Comment by ghost** [comment]
The one you ordered is actually similar to the adapter I used.
Besides, you also need ipex4 extended cable to extend the antenna.

**Comment by egore24** [comment]
Thank you! 

I just ordered three as well: https://www.amazon.com/gp/aw/d/B07L3DGJ2D?ref=ppx_pt2_mob_b_prod_image

Hopefully all of these items will work!

**Comment by ghost** [comment]
I believe it would be work with all Apple devices.
It works with my Magic Mouse 2 and other bluetooth devices.
Besides, most hackintoshers confirm that this card is working with Apple Watch flawlessly, just as normal MBP.

**Comment by ctermiii** [comment]
> I believe it would be work with all Apple devices.
> It works with my Magic Mouse 2 and other bluetooth devices.
> Besides, most hackintoshers confirm that this card is working with Apple Watch flawlessly, just as normal MBP.

yes, unlock  handoff sidecar airdrop all ok.

**Comment by egore24** [comment]
As thought, the adapter mentioned above doesn't only not fit, but it is the wrong form factor for this application. That being said, does anyone know it it's an option to remove the silver receiver end off of this adapter to be re-soldered to a flex cable in an effort to recreate the OP's china linked adapter? Thanks.

https://www.amazon.com/BCM94360CS2-BCM943224PCIEBT2-Card-Adapter-Hackintosh/dp/B01JGERLOS/ref=pd_ybh_a_22?_encoding=UTF8&psc=1&refRID=2H8K3X3P4HP17134SQH5

**Comment by rossna** [comment]
To everyone looking at this thread later on: There is now a card that fits natively and has the same features as the BCM94360CS2; the BCM94360NG. They run for about $50 on Amazon or eBay, but it is the same exact chipset as the CS2.

**Comment by egore24** [comment]
Thank you! I didn't see it specifically mentioned, but can you confirm Apple Watch unlock feature also is operating as it should with this card?

**Comment by rossna** [comment]
I cannot confirm personally. My card is on order right now and I do not have an Apple Watch.

However, two sources claim that AW unlock works perfectly with this card:

https://github.com/osy86/HaC-Mini/issues/197

https://www.reddit.com/r/hackintosh/comments/fegjar/found_bcm94360ng_wifi_natively_supported_replace/

**Comment by egore24** [comment]
Excellent, thanks again. I have one in order now as well. Will report back on AW and other functionality.

**Comment by egore24** [comment]
Confirmed. So far, the BCM94360NG card is performing perfectly. I would recommend this card as a replacement, offering full hackintosh functionality.

**Comment by ghost** [comment]
@egore24 Good to hear that. That card would be added to support list. BTW, which adapter did you use with, I will also add the link of the adapter to support list.

**Comment by rossna** [comment]
No adapter necessary; it's a regular M.2 NGFF card that began to be sold in January of this year. No kexts necessary, exactly like the BCM94360CS2, except in M.2 form.

**Comment by egore24** [comment]
As rossna said, no adapter. I returned the Bcm94360cs2, antenna extensions and the adapter. Instead I ordered and most recently referring to the BCM94360NG, which is a drop-in replacement M.2 form factor card. No adapter needed and stock antenna wires snapped right in. All desired functions are working as expected. Handoff, airdrop, AW unlock, etc. Very pleased. Certainly the preferred solution.

**Comment by ghost** [comment]
Thanks for testing, BCM94360NG would be added to support list. Problem solved.
