### ISSUE TITLE
FaceTime & iMessage can't login

### ISSUE THREAD

**Issue by ctermiii** [the-Quert/XPS-9360-macOS#18]
iCloud and App Store ok;
but facetime show this account has no reachable addresses;
iMessage sad an error accurred during authentication.

**Comment by ghost** [comment]
Real MBP/iMac/Mac Mini's smUUID and Serial Number is required to activate Facetime and iMessage.

**Comment by ctermiii** [comment]
Yes I have tried several serial numbers from genmacserial ,but still cant.
I will work on it

**Comment by ctermiii** [comment]
its ok now . change serial number. thanks.
