### ISSUE TITLE
XPS 9350

### ISSUE THREAD

**Issue by tlefko** [the-Quert/XPS-9360-macOS#19]
hey @the-Quert, any chance this would work the i7 3K HD 520 XPS 13?

**Comment by tlefko** [comment]
I tried to make my own repository but i absolutely cannot get the sleep wake to work without a black screen. Did you encounter this?

**Comment by ghost** [comment]
Since HD520 is SkyLake based, you have to change ig-platform-id to 0x19160000 from config.plist

**Comment by theQuert** [comment]
Problem solved, case closed.
