### ISSUE TITLE
Static sound feedback from keyboard and touchpad 

### ISSUE THREAD

**Issue by R1MnTnA** [the-Quert/XPS-9360-macOS#20]
Hi @the-Quert, First thank you for your work on this git. 

I installed 10.15.4 on my XPS 9360 with BIOS 2.13. For the most part everything was working fine for me up until I put the two i7-8550 cpufriend kexts in /library/extensions and ran the rebuild cache. I then ran the combo-jack command and then rebuilt the cache. I then rebooted. Now I’m hearing a static feedback every time I click the touchpad or some keys on the keyboard. I’ve tried to use the uninstall script I got from the combo jack git and removed the kext file from clover/kexts, rebuilt the cache and restarted but that didn’t help. I then removed the cpufriend kexts and rebuilt the kexts, but that didn’t help either.

Do you know how I can get back to normal here? Have you ever experienced a problem like this?

**Comment by ghost** [comment]
Since this condition never happened in my installation experience, reinstall the whole system would be recommended.

**Comment by theQuert** [comment]
Problem is not traced anymore, case closed.
