### ISSUE TITLE
right usb power problem?

### ISSUE THREAD

**Issue by TaiPhamD** [the-Quert/XPS-9360-macOS#22]
<img width="557" alt="Screen Shot 2020-05-14 at 5 37 41 PM" src="https://user-images.githubusercontent.com/10516699/82003528-71720980-9615-11ea-8119-30e9c65c8104.png">

anyone have this issue? i did a google search and it seems other people have it on linux and windows too. My left USB is just fine. When this happens it actually kill my internal BLE USB. Once i disconnect the device then my internal BLE USB recovers.

**Comment by ghost** [comment]
This issue only appear once on my device. After reboot and replug the cable, it's working fine so far.

**Comment by TaiPhamD** [comment]
I got past this by doing an EC rename from ECDV to EC in addition to using usbhub fix.kext.

It stopped the pop up from wake. However my USB port actually doesn’t work but this is good enough for me for now. I think the root of the issue is the microchip internal usb hub that’s connected to HS01

**Comment by ghost** [comment]
Which boot loader do you use with ? 
If working with `OC`, more improvement would be done in future releases.
For now, it's recommended to use `Clover` as default boot loader.

**Comment by TaiPhamD** [comment]
I am using OC . Do you mind giving me an export of your XHC tree from IOREG ? I want to compare some power properties between yours and mine (mostly the SS01 and SS02 ports). Thank you.

**Comment by TaiPhamD** [comment]
Fyi I finally figured out my issue . It was the broken right USB port. Luckily I found a USB daughter board replacement and now it’s working perfectly !

![E330389E-34AF-4ABF-82B2-B171D45C9305](https://user-images.githubusercontent.com/10516699/84729375-65e16d80-af48-11ea-824d-06abf52858d4.jpeg)
