### ISSUE TITLE
DW1560  Handoff 

### ISSUE THREAD

**Issue by wdrich** [the-Quert/XPS-9360-macOS#24]
Can the handoff function of dw1560 work normally?

**Comment by ghost** [comment]
Yap, handoff on DW1560 is working normally.

**Comment by wdrich** [comment]
I do not know why? The same kext, DW1830 can work well, but DW1560 can't work

**Comment by ghost** [comment]
Do you mean the kexts in `/DW1560` from my repo?

**Comment by wdrich** [comment]
yes! I use the kexts in /DW1560 from repo!

**Comment by ghost** [comment]
The kexts in `/DW1560` work with DW1560 well.

**Comment by wdrich** [comment]
Thank you！But I did not fixed this bug。
Any one could find me,but I could not find anyone!

**Comment by ghost** [comment]
Try deleting the kexts, `rebuild_cache` with my shell script, then reboot.
After reboot, add the kexts in `/DW1560`, and `rebuild_cache` again.

**Comment by wdrich** [comment]
thank you very much！

**Comment by ghost** [comment]
Problem solved, case closed.
