### ISSUE TITLE
Original dsdt hotpatches breaks dual-booted Windows

### ISSUE THREAD

**Issue by weimin-liu** [the-Quert/XPS-9360-macOS#26]
I used to use the original dsdt hotpatches (same with those from the darkvoid's repo), but they tend to render the dual-booted Windows unstable since the patches are also applied to Windows using opencore. The dsdt hotpatches that used until last commits works well on both macOS and Windows that booted from opencore.

**Comment by ghost** [comment]
Thanks for comments. 
Problem solved, case closed.
