### ISSUE TITLE
Poor SSD write speeds

### ISSUE THREAD

**Issue by callumbloomfield** [the-Quert/XPS-9360-macOS#28]
Firstly, thanks putting all this together - besides this issue, everything worked flawlessly on the first time. Not really sure where to start with fixing this, so hopefully someone can point me in the right direction.

The only issue I'm having is very poor write speeds to the NVME SSD. The read speeds are as expected, but the slow write speeds are very noticeable in day to day use. (the old SATA SSD in my desktop hackintosh is twice as fast)

[See this](https://imgur.com/a/slS1nRE) screen recording I made showing a disk read/write test. It appears to write fine at around 800mb/s momentarily, before crashing to 250mb/s. Again, read speeds seem to be ok.

My specs:

XPS 13 9360
FHD Display
i5 7200u
256gb Toshiba XG4 SSD

My install:

SSD formatted to APFS with 4K byte sectors
Have tried TRIM enabled and disabled -enabling TRIM seems to reduce the write speeds slightly, no effect on read speeds.

I've had Windows and Ubuntu on this laptop in the past - both had no issues with write speeds.

Thanks!

**Comment by the-Quert** [comment]
Try running the speed test under Windows/Linux again, or reinstall macOS again.

- Kinda busy on other stuffs these days, more researches would keep going in few weeks.

- Feel free to report any issues, and maybe I will do it tomorrow.
