### ISSUE TITLE
Headphone or Speaker work with buzz or no sound

### ISSUE THREAD

**Issue by ghost** [the-Quert/XPS-9360-macOS#3]
If you get into the situation refer to title...

Open System Preference -> Sound -> Input
Then minimize the window, don't close it.
---The function would act normal as soon as doing as below---
If there are other solutions?
-> As far as I know...it's still a bug...Nope !
-> Just sharing the solutions so far I found.

---Photo is Embedded---
![Screen Shot 2019-09-07 at 10 15 21 PM](https://user-images.githubusercontent.com/19849526/64476125-beb3f680-d1bd-11e9-808e-2e0bacf06db0.png)

**Comment by the-Quert** [comment]
Since there is a temporary solution to the issue, issue closed.

**Comment by ghost** [comment]
Since there is a temporary solution to this issue, issue closed.
