### ISSUE TITLE
Defaults to Opencore bootmenu

### ISSUE THREAD

**Issue by actuallyliam** [the-Quert/XPS-9360-macOS#30]
I used the GibMacOS selected 1, inserted a 16GB USB, created it. It boots to Clover without copying on 
![OpenCore](https://user-images.githubusercontent.com/67041888/84862814-3309b780-b0b7-11ea-9e16-926c675d5f6f.jpg)
anything from this folder. But once I overwrite (I copy over the already existing files) the EFI folder with the contents this repository it boots into Opencore bootmenu with no OS found and just keeps looping until I shut it down.

**Comment by ghost** [comment]
Make sure boot entries from bios is set correctly.
Also, try booting with `Clover` to make sure if macOS is installed completely.

- Feel free to report any issues, and maybe I will do it tomorrow.
