### ISSUE TITLE
README Issue with Wifi

### ISSUE THREAD

**Issue by jamescochran** [the-Quert/XPS-9360-macOS#37]
In the README it has 

`cp /DW1560/*.kext /CLOVER/kexts/Other`

Where it should have a -R flag to cp the kexts as they look like folders to MacOS and it needs to drop the trailing slash since we are already in /Volumes/EFI/EFI

`cp -R DW1560/*.kext CLOVER/kexts/Other`

**Comment by ghost** [comment]
Changes have been merged.

Problem solved, case closed.

Contributor: @jamescochran
