### ISSUE TITLE
oc and sleep

### ISSUE THREAD

**Issue by go-david** [the-Quert/XPS-9360-macOS#41]
oc boot conifg.plist needs to remove VoodooInput, otherwise you can’t enter the system
Some 9360s are powered off without power, and cannot wake up from sleep. You need to enter ubuntu live to shut down once, and then you can sleep normally. As for why, I don’t know why.

**Comment by theQuert** [comment]
`VoodooInput` has been removed before, thanks for your support.
Sleep problem on 9360 is fixed before, if you still encounter this issue, please upload the tree of your EFI folder.

- Feel free to file any issues, and maybe I will do it as soon as I can.

**Comment by theQuert** [comment]
Goto [Here](https://github.com/theQuert/XPS-9360-macOS/issues/44).
- Problem Fixed.

- Feel free to file any issues, and maybe I will do as soon as I can.

**Comment by theQuert** [comment]
Problem solved, case closed.
