### ISSUE TITLE
commit a8ac7b7078d9aa840d0b666fc1971672386e5447 Unable to boot without VoodooInput.kext installed

### ISSUE THREAD

**Issue by egore24** [the-Quert/XPS-9360-macOS#44]
Latest commit (commit a8ac7b7078d9aa840d0b666fc1971672386e5447) for OC does not boot without first installing VoodooInput.kext (additional to your repo). Appears to be a bug in your config or omission of this needed kext?

Thanks.

**Comment by theQuert** [comment]
`VoodooInput` is removed before.

- Feel free to file any issues, and maybe I will do as soon as I can.

**Comment by egore24** [comment]
Lines 1081-1096 of OC config file still reference the VoodooInput.kext being installed, thus causing the install error of your repo, as the VoodooInput.kext is not present in the kext folder. Should the config file be edited to remove the reference to the kext or, it remain as is and the kext added to the kext folder?

			<dict>
				<key>BundlePath</key>
				<string>VoodooInput.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooInput</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>

Thanks much.

**Comment by theQuert** [comment]
Thanks for inspection.
`VoodooInput.kext` is removed before, but forgot deleting lines from `config.plist`.

- Problem Fixed:  `VoodooInput` is removed from `config.plist`.
- Thanks a lot, feel free to file any issues, and maybe I will do as soon as I can.

**Comment by theQuert** [comment]
Problem solved, case closed.
