### ISSUE TITLE
No WiFi on BigSur

### ISSUE THREAD

**Issue by TrustedDeveloper** [the-Quert/XPS-9360-macOS#52]
The current OC configuration does not seem to support the DW1560, though Bluetooth remains functional.
I've attached my updated OC with functioning WiFi for those who are interested.

[OC 3.zip](https://github.com/theQuert/XPS-9360-macOS/files/5541367/OC.3.zip)

**Comment by StormBreaker99** [comment]
How did you managed to update? I'm on Catalina and I'd like to update to Big Sur.
Thank You! :)

**Comment by theQuert** [comment]
Tried the latest version of repo, everything is already set for Big Sur.

**Comment by TrustedDeveloper** [comment]
Great, thank you for your hard work!
