### ISSUE TITLE
[OC] Webcam Black Screen

### ISSUE THREAD

**Issue by jramzz1** [the-Quert/XPS-9360-macOS#53]
Not sure if this was a problem pre Catalina but since 10.15 and now in Big Sur (for me at least), the webcam only works one time after boot. For example opening photo boot I get an image but then closing the app and reopening there is only a black screen in the view finder until a reboot. This happens with UVC2FacetimeHD.kext, FacetimeHD.kext as well as no webcam kext at all so I believe it's not a kext issue? 

Has anyone experienced this and if so found a solution for it? This appears to be the only "major" issue I've experienced.

<img width="1015" alt="Screen Shot 2020-11-15 at 9 14 14 PM" src="https://user-images.githubusercontent.com/36009529/99216973-9437d300-279c-11eb-90d6-679ed6624bfd.png">

<img width="502" alt="Screen Shot 2020-11-15 at 11 42 44 PM" src="https://user-images.githubusercontent.com/36009529/99216837-4fac3780-279c-11eb-92f2-9cf336cced1f.png">

**Comment by StormBreaker99** [comment]
How did you managed to update? I'm on Catalina and I'd like to update to Big Sur, and when I try to update, from "Software Update", it fails.
Thank You! :)

**Comment by RicKrauel** [comment]
I have the same issue since Catalina. Worked fine in Mojave.

Tried all the kext you already mentioned, nothing worked. Resorted to using an external one if I need a webcam.

**Comment by theQuert** [comment]
The 'Disable Camera' option could be set 'True' in BIOS.
Then, camera works fine under both Catalina and Big Sur.

**Comment by jramzz1** [comment]
@StormBreaker99: I went from clover to opencore so I started off from scratch again. I'm not sure how it would work if you would want to just "update" sorry.

@Richylitschy: Do you remember changing anything with the usb mapping (DSDT stuff) when you went from mojave -> catalina? The external webcam might be the way to go. 

@theQuert:  Disable Camera is false in BIOS, like previously mentioned camera works on first startup and often even after letting the machine go to sleep for 30-60mins. Problem seems to be that after turning off the webcam and attempting to turn it on again it fails to load up. Not sure if this is might be some usb timeout or driver issue?

I'll keep poking around, will post back if a solution is found.

**Comment by StormBreaker99** [comment]
@jramzz1 i tried switching to OC fro a fresh install, but i'm getting "OC: Driver AudioDxe.efi at 1 cannot be found!"
I'm new to this, can ya help me out?

**Comment by theQuert** [comment]
From 'Mojave' to 'Big Sur', DSDT of USB mapping never changed. 
Since this issue remained, I will keep focusing on solution.

**Comment by xseignard** [comment]
Here is my workaround

When I have troubles with the webcam, here is the command I run in the terminal. After that, the camera is running again.
`sudo killall VDCAssistant`

**Comment by theQuert** [comment]
Thanks for testing, solution is added to README file.

Problem solved, case closed.

**Comment by jramzz1** [comment]
@xseignard thanks for the suggestion, however it doesn't seem to work for me unfortunately.

The following repo for the (xps 9343) also appears to have this issue so might be a dell webcam issue?
https://github.com/fredldotme/Dell-XPS13-9343-Hackintosh

**Comment by xseignard** [comment]
@jramzz1 I confirm the solution I provided ain't working for the XPS I'm working on right now and face the same exact problem as you.
Here is the vid/pid of the webcam: VendorID_3141 ProductID_26380

Any idea ?

**Comment by jramzz1** [comment]
@xseignard I opened up another issue here: https://github.com/theQuert/XPS-9360-macOS/issues/64 where I dug into this a bit further. No solution yet but basically the 3034 webcams seem to be the only ones that work correctly.
