### ISSUE TITLE
Help, I killed Webcam?!

### ISSUE THREAD

**Issue by macmeister1967** [the-Quert/XPS-9360-macOS#56]
I tried OBS, and lost webcam entirely, removed obs-virtual-camera.plugin and got webcam back - but only without FacetimeHD.kext - otherwise no webcam.

I'll try gettng fresh versions of all the kexts and plugins, and see if that helps. Do I need a copy of FacetimeHD.kext in /L/E as well ??

Cheers for a great repository !!!

**Comment by theQuert** [comment]
Problem solved, see the "Fix Webcam Black Screen" part in README.
Case closed.
