### ISSUE TITLE
LITEON NVMe doesn't appear in Disk Utility

### ISSUE THREAD

**Issue by rs189** [the-Quert/XPS-9360-macOS#6]
Hello, after hours of pain i managed to get into Catalina Installer however i am stuck in Disk Utility because there is no internal NVMe showing up, i only see my USB drive in the list, my XPS 13 9360 variant has Liteon CX2 512GB NVMe drive (It doesn't support 4K sectors), so is it possible to install it on this NVMe?

**Comment by ghost** [comment]
To solve the problem, I have add patch to config.plist.
The config.plist path to support LITEON is under /CLOVER/config for LITEON
Try one config each time , and remember to replace the original config with the one which is compatible with LITEON.

**Comment by ghost** [comment]
Since solution and patches are add to Clover and README, case close.
