### ISSUE TITLE
Why the Wallpapers?

### ISSUE THREAD

**Issue by rozenmd** [the-Quert/XPS-9360-macOS#61]
The README instructions say:
> Copy the whole repository to EFI partition to the path mentioned above. (You have to create an empty EFI directory, and put the whole repo in it).

The Wallpapers directory's size (478,085,111 bytes (478.2 MB on disk) for 35 items) exceeds the size of the EFI partition (200MB).

May I suggest either deleting the Wallpapers directory (and purging it from git history), or updating the README?

**Comment by theQuert** [comment]
Problem fixed: 'Remove the "Wallpapers"'
Case closed.
