### ISSUE TITLE
Mojave build 18G7016 support?

### ISSUE THREAD

**Issue by macmeister1967** [the-Quert/XPS-9360-macOS#62]
This was a Security Update, so god only knows what it replaced... it was sizable tho, and looking at the Apple docs, a lot of regular hardware drivers (video/audio etc) were "fixed"

I will be happy to test this when I try the rolled-back OC boot...

**Comment by theQuert** [comment]
Please try the old build with `Clover` configuration.

**Comment by macmeister1967** [comment]
I'm using Clover configuration... I am also concerned about the amount of boot failure on other modern Dell XPS hackintoshes running OpenCore, so I will stick with my (your) dual-boot Clover setup :-)

**Comment by theQuert** [comment]
Repo updated, try the latest build with macOS Big Sur.
