### ISSUE TITLE
[OC] Black Webcam Update

### ISSUE THREAD

**Issue by jramzz1** [the-Quert/XPS-9360-macOS#64]
Link to previously opened issue with explanation of problem: https://github.com/theQuert/XPS-9360-macOS/issues/53 

Unfortunately the "killall vdcassistant" that was accepted as the solution doesn't work in my case. However I have access to 2 other 9360's and after booting into macOS on those I noticed that the webcams worked with no issues. Inspecting further I found that the hardware info on those were as follows:

- VendorID_3034 ProductID_22146 (1080p Display)
- VendorID_3034 ProductID_22146 (QHD Display)

While on my personal laptop it being

- VendorID_3142 ProductID_26380 (QHD Display)

It appears the webcams that are VendorID_3034 (same as @theQuert per readme) seem to be working correctly while the rest don't? I should include that this was all done with no webcam kext at all and attempting to use a modified FaceTimeHD.kext either had no effect or killed the webcam completely. Not sure if I'm missing somewhere else where I should be looking at ACPI possibly or if it's simply a compatibility issue with this specific webcam and this vendorID?

**Comment by angsanley** [comment]
Facing the same problem also with:
VendorID_3141 ProductID_26380 (QHD Display)

`killall vdcassistant` doesn't work for me too.

It seems like the webcam works for the first time after boot for some apps only, one of them is OBS. My current workaround is to use OBS Virtual Camera and making sure no other apps is using the camera directly except OBS. Not an ideal solution though, as OBS is very resource intensive.

**Comment by jramzz1** [comment]
I personally ended up swapping out the screen with one of my other xps's with the "VendorID_3034 ProductID_22146" webcam. If I have a chance to mess with the conflicting webcam again I'll post any updates.

However it seems like we know what the problem is now, hopefully someone more knowledgeable is able to pin point a solution for it. If possible to avoid having to swap out displays or using third-party software.

**Comment by RicKrauel** [comment]
Have the same issue with UVC Camera VendorID_3141 ProductID_26380.

Works only one time after boot / coming out of sleep. Don’t use the webcam much, but its a funny issue, because it worked fine with Catalina. Current workaround for me is to put the laptop to sleep and wake it up immediately. This way the camera works as long as I do not close the app that is accessing the camera.

Seems to me that the issue is related to turning off the camera after an app accessed it, as it works again after system-wide sleep.

**Comment by RicKrauel** [comment]
Fyi: this seems to be fixed after updating to 12.1 Monterey! Works now for me without errors, even switching camera apps.

**Comment by theQuert** [comment]
Problem solved, case close.
