### ISSUE TITLE
OC Configuration Doesn’t Boot

### ISSUE THREAD

**Issue by TrustedDeveloper** [the-Quert/XPS-9360-macOS#65]
Hey there,
I am having some issues with the latest OC build.
Whenever I try to boot with it, OC throws an error saying: `Error: audiodxe.efi not found`.
I went on to populate the `Drivers` folder with the default drivers from the stock OC build.
Finally, when I tried to boot up, there was an issue with CPUFriend.kext.
Am I doing something wrong? Is the config.plist ready to use, or does it require additional tinkering?
Thanks,
Sam

**Comment by theQuert** [comment]
Configuration is still under fixing and maintenance, pls try the oldest build.

**Comment by theQuert** [comment]
Problem solved, case closed.
