### ISSUE TITLE
 Brightness not working - BigSur 11.4 / XP3 13 9360 i7 7500u Full HD screen [Solution inside]

### ISSUE THREAD

**Issue by PankovSerge** [the-Quert/XPS-9360-macOS#70]
Please help with non-working brightness keys / wrong display info for this configuration: 

BigSur 11.4 / XP3 13 9360 i7 7500u Full HD screen

Intel HD Graphics 620:

  Chipset Model: Intel HD Graphics 620
  Type: GPU
  Bus: Built-In
  VRAM (Dynamic, Max): 1536 MB
  Vendor: Intel
  Device ID: 0x5916
  Revision ID: 0x0002
  Metal Family: Supported, Metal GPUFamily macOS 2

BrightnessKeys.kext exists on OC configuration. 

![photo_2021-06-02_19-25-22](https://user-images.githubusercontent.com/5969391/120516780-66cd1280-c3d8-11eb-8647-5a2b8cc32dbd.jpg)

[config.txt](https://github.com/theQuert/XPS-9360-macOS/files/6586123/config.txt)

Thanks in advance!

**Comment by suservu123** [comment]
Wrong SMBIOS ???

**Comment by go-david** [comment]
Lack of rename patch, find the previous version, just add it up。

**Comment by tanagram27** [comment]
Having the same problem with an i7 8550u in my xps.

**Comment by dvrkoo** [comment]
Same issue here with 9360

**Comment by PankovSerge** [comment]
Fixed in #75, @theQuert  please check!
