### ISSUE TITLE
BCM94360NG uplink speed is very low

### ISSUE THREAD

**Issue by filipdadgar** [the-Quert/XPS-9360-macOS#74]
Love the awesome work!

I been a hackintosh fan for ages and have some experience since old days with random builds.
Since a few years back I've been running MacOS on Dell XPS 9360 7500u. With mixed satisfaction. 

I took in the advice to change my dw1560 to BCM94360NG and it does work OOB, but lately I've been bugged by the fact that the uplink speed is very low.

I have 150/150 ISP and have invested tons in Unifi stuff. So I know the quality of the WIFI, signal and what not is good to not be the source.

Download speeds are satisfactory, but upload doesnt ever reach 10Mbit.
(Since I discovered this, coincidently TimeMachine (running on Synology in same network) has started to missbehave as well, so no backups suddenly!) 

I've reenabled AirportBrcmFixup as well but still bad.

Any advice would be much appreciated!

**Comment by jamescochran** [comment]
Interesting. I'm uploading a file to my server now and I'm getting well over 45 Mbps. I haven't really noticed any issues and I think that's about what can be expected out of 802.11n. I'm also on Unifi stuff and I'm sitting in the same room as my Unifi AP LR. I double checked and the card does support ac but I'm 99% sure these APs only go to 802.11n. The new version 6 has ac I think. $99 each.... maybe it's time for me to upgrade :)

Anyway, I'm sorry I wish I could help. Maybe double check your connections and ensure the antenna are seated correctly. I'm running OpenCore and I do have the AirportBrcmFixup kext in the kext fodler. Attaching a screen shot of all the kexts I have in /EFI/OC/kexts

![Screen Shot 2021-10-29 at 12 16 15 PM](https://user-images.githubusercontent.com/1735821/139468625-4dfdb048-7656-4730-8268-a5320bb60860.png)

**Comment by filipdadgar** [comment]
Thank you for getting back!

I have identical set of kexts. So it must be hw related I guess. Any hints on how to check wifi logs or logs for this specific card? Maybe its firmware problem?

best,
Filip

**Comment by jamescochran** [comment]
I don't know much about checking that, no. Did you open it back up and ensure the antenna are hooked up properly? If it were me I'd start there. Maybe even buy a second one to see if it works better and send one back.

**Comment by filipdadgar** [comment]
Thank you! What I did was to put the DW1560 back in, and surprisingly it just started without issues and I have no speed issues. So happy right now. Once I get bored, I will probably buy a new NG and test. :)
