### ISSUE TITLE
Touchpad isn't working (10.15.3 Installer) 

### ISSUE THREAD

**Issue by cedobr** [the-Quert/XPS-9360-macOS#8]
My XPS 9360 is currtently still on 10.13 and the touchpad is working fine. (Bios 2.62). I've downloaded your clover configuration and replaced the folders on the usb efi partition and booted in to the installer. In the installer the trackpad is not working (moving the mouse / clicking). Has anyone else ever experieced that problem ?

**Comment by ghost** [comment]
During installation, you may experience the mouse problem.
It's because the VoodooHID.kext may not injected during installation.
To solve the problem, you need external mouse connection on your own.
When booting into the system after installation, trackpad would work as normal.

**Comment by cedobr** [comment]
I've still had the problem after the installation. The 2C and HID .kext in your repo are not up to date. There is a newer release. (2.3) https://github.com/alexandred/VoodooI2C/releases 
However my Dell now runs perfectly, thanks a lot for your work :)

**Comment by ghost** [comment]
Although the I2C and HID are not the newest version, it still works well on my fresh install last month on Catalina 10.15.2
Well, the kext will be updated in few days.
