### ISSUE TITLE
Thank you very much for your work, this can make the lightning interface hot plug

### ISSUE THREAD

**Issue by HotMaker** [the-Quert/XPS-9360-macOS#9]
https://1drv.ms/u/s!Ai021ZyMKLF25WS1s844vWyLYYaB
i have try 
very nice！

**Comment by ghost** [comment]
Thunderbolt 3 is testing to be hot-plugged  with the current repo, the kext will be tested and decided  whether adding to repo or not.
Thanks for the work.

**Comment by HotMaker** [comment]
Then, can you look into the shutdown button. Some devices press the shutdown button to pop up the shutdown menu

**Comment by HotMaker** [comment]
i try PWRB in https://github.com/daliansky/P-little

But nothing happens

**Comment by ghost** [comment]
1. IOElectrify.kext would not be added to current repo, cause hot-plugged is working normally, and PCI device is also recognized.
2. What would you expect when "Power button" is pressed ?

**Comment by HotMaker** [comment]
https://lh3.googleusercontent.com/proxy/5TVwPPqk4fvtC_nD3XbhrH7MDIEv4mo-F5HIJs6zfHbFzVI3kMSkztN-Ks1N8YbRzDpx3hLcA06T-IjA8Xghmi1OYc4g5LcSflEONuz-FUtIb8Rgesi_WtY
I have successfully called it out before, but then it is gone.
Hot plugging may be the difference between our devices. I'm 9360 i5 8250u. When I use it, there is no hot plugging. . .
Thank you very much for your efforts. I tried almost all 9360 EFI on GitHub. You are the perfect one. . .

**Comment by ghost** [comment]
1. Since hot-plugged problem would occur on some 9360 i5 8250u, IOElectrify.kext will be added to repo recently.
2. To activate menu when "Power button" is pressed, "rename PBTN to PWRB" is needed, will trying to improve later.

**Comment by nmm2401** [comment]
> 1. Since hot-plugged problem would occur on some 9360 i5 8250u, IOElectrify.kext will be added to repo recently.
> 2. To activate menu when "Power button" is pressed, "rename PBTN to PWRB" is needed, will trying to improve later.

me use 8250u, i think don't need it

**Comment by nmm2401** [comment]
> https://lh3.googleusercontent.com/proxy/5TVwPPqk4fvtC_nD3XbhrH7MDIEv4mo-F5HIJs6zfHbFzVI3kMSkztN-Ks1N8YbRzDpx3hLcA06T-IjA8Xghmi1OYc4g5LcSflEONuz-FUtIb8Rgesi_WtY
> I have successfully called it out before, but then it is gone.
> Hot plugging may be the difference between our devices. I'm 9360 i5 8250u. When I use it, there is no hot plugging. . .
> Thank you very much for your efforts. I tried almost all 9360 EFI on GitHub. You are the perfect one. . .

me 8250u, u feel stable with IO ?

**Comment by ghost** [comment]
IOElectrify.kext deleted.
